spring:
  application:
    name: terrible-task-launcher

  cloud:
    stream:
      bindings:
        input:
          destination: terrible-task-launcher
        output:
          destination: queue.pretty.log.messages
    deployer:
      local:
        maximum-concurrent-tasks: 5

